name: Repomix - Create llms.txt

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'llms.txt'
  workflow_dispatch:

jobs:
  update-summary:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run repomix and prepend header
        run: |
          HEADER="<!--\nThis file contains all of the markdown documentation from the project ${{ github.repositoryUrl }}.\n Generated automatically using Repomix.\n-->\n\n"

          npx repomix --compress --style markdown \
            --no-file-summary \
            --include "*.md,**/*.md" \
            --output _llms.txt

          echo -e "$HEADER$(cat _llms.txt)" > llms.txt
          rm _llms.txt

      - name: Commit and push if changed
        run: |
          git config user.name "Repomix Action Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add llms.txt
          if ! git diff --cached --quiet; then
            git commit -m "Generate+update llms.txt via repomix"
            git push
          fi
